# MySQL.  Versions 4.1 and 5.0 are recommended.
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysqll
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386"     gem install mysql --
#   --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native
#     architecture
# On Windows:
#   gem install mysql
#       Choose the withn32 build.
#       Install MySQL and put its /bin directory on yourur path.
# And be sure to use new-style password hashing:password
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  database: alarms_development
  pool: 5
  username: alarms
  password: alarms
  host: localhost
#
#                       25
#
#                       26
#
#                       # Warning: The database defined as "test" will be
#                       erased and
#
#                       27
#
#                       # re-generated from your development database when you
#                       run   "rake".
#
#                       28
#
#                       # Do not set this db to the same as development or
#                       production.
#
#                       29
#
#                       test:
#
#                       30
#
#                         adapter: mysql
#
#                         31
#
#                           encoding: utf8
#
#                           32
#
#                                    database: H2TwinSystem_test
#
#                                    33
#
#                                      pool: 45
#
#                                      34
#
#                                        username: H2TwinDB
#
#                                        35
#
#                                          password: H2TwinDB
#
#                                          36
#
#                                            socket:
#                                            /var/run/mysqld/mysqld.sock
#
#                                            37
#
#                                            38
#
#                                            production:
#
#                                            39
#
#                                              adapter: mysql
#
#                                              40
#
#                                                encoding: utf8
#                                                       
#                                                       41
#
#                                                         database:
#                                                         H2TwinSystem_production
#
#                                                         42
#
#                                                           pool: 15
#
#                                                           43
#
#                                                             usernamename:
#                                                             H2TwinDB
#
#                                                             44
#
#                                                               password:
#                                                               H2TwinDB
#
#                                                               45
#
#                                                                 socket:
#                                                                 /var/run/mysqldld/mysqld.sock
#
#                                                                 46
#
#                                                                 47
#
#                                                                 production_with_scheduler:
#
#                                                                 48
#
#                                                                   adapter:
#                                                                   mysqlysql
#
#                                                                   49
#
#                                                                     encoding:
#                                                                     utf8
#
#                                                                     50
#
#                                                                       database:
#                                                                       H2TwinSystem_production
#
#                                                                           51
#
#                                                                             pool:
#                                                                             45
#
#                                                                             52
#
#                                                                               username:
#                                                                               H2TwinDB
#
#                                                                               53
#
#                                                                                 password:
#                                                                                 H2TwinDB
#
#                                                                                       54
#
#                                                                                         socket:
#                                                                                         /var/run/mysqld/mysqld.sock
#                                                                                           
